[package]
name = "tls_client"
version = "0.1.0"
authors = ["Cong Lian <liancong22@gmail.com>"]

[dependencies]
hyper = "0.12"
pretty_env_logger = "0.2"
hyper-rustls = "0.14.0"
rustls = "0.13"
tokio-core = "0.1.7"
futures = "0.1"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"

