[package]
name = "tls_server_v2"
version = "0.1.0"
authors = ["Cong Lian <liancong22@gmail.com>"]

[dependencies]
futures = "0.1"
http = "0.1"
hyper = "0.12"
rustls = "0.13"
tokio-io = "0.1.1"
tokio-rustls = "0.7"
tokio-tcp = "0.1"
webpki = "0.18.1"
webpki-roots = "0.15"
tokio = "0.1"
